on:
  push:
    branches:
      - DEV # Change this to your respective branch
permissions:
  id-token: write
  contents: read

jobs:
 build:
   runs-on: [self-hosted, dev-runner]
   steps:
      - name: Checkout code
        uses: actions/checkout@v4
        run: |
           cd /home/ubuntu
           mkdir surajj
